kind: Service
apiVersion: v1
metadata:
  name: howard-moomboo
  namespace: ingress-nginx
spec:
  ports:
    - name: k3s-ingress
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 0
---
kind: Endpoints
apiVersion: v1
metadata:
  name: howard-moomboo
  namespace: ingress-nginx
subsets:
- addresses:
  - ip: 10.17.12.235
  ports:
  - port: 443
    name: k3s-ingress
