---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./secrets/home-workers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
