# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: commitstew-com-insecure
#   namespace: traefik-production
# spec:
#   entryPoints:
#     - web
#   routes:
#   - match: Host(`giovanni.commitstew.com`) || Host(`nwinter.commitstew.com`) || Host(`alys.commitstew.com`) || Host(`dan.commitstew.com`) || Host(`xenocid.commitstew.com`) || Host(`jordan.commitstew.com`) || Host(`alys.commitstew.com`) || Host(`dan.commitstew.com`) || Host(`xenocid.commitstew.com`) || Host(`jordan.commitstew.com`) || Host(`brian.commitstew.com`) || Host(`nick.commitstew.com`) || Host(`alex.commitstew.com`) || Host(`clarissa.commitstew.com`) || Host(`luke.commitstew.com`) || Host(`mike.commitstew.com`) || Host(`max.commitstew.com`) || Host(`jay.commitstew.com`) || Host(`sergii.commitstew.com`) || Host(`cole.commitstew.com`) || Host(`forrest.commitstew.com`) || Host(`chris.commitstew.com`) || Host(`echodaniel.commitstew.com`) || Host(`edyson.commitstew.com`) || Host(`clive.commitstew.com`) || Host(`byorgey.commitstew.com`) || Host(`kim.commitstew.com`) || Host(`kb.commitstew.com`) || Host(`kevin.commitstew.com`) || Host(`mbork.commitstew.com`) || Host(`shanaqui.commitstew.com`) || Host(`philip.commitstew.com`) || Host(`bee.commitstew.com`) || Host(`adam.commitstew.com`) || Host(`mary.commitstew.com`) || Host(`martin.commitstew.com`) || Host(`dreev.commitstew.com`) || Host(`aian.commitstew.com`) || Host(`commitstew.com`)
#     kind: Rule
#     services:
#     - name: commitsto-staging-x-commitsto-staging-x-hephy-stg
#       namespace: vcluster-hephy-stg-turkey-local
#       port: 80
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: commitstew-com
#   namespace: traefik-production
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - match: Host(`giovanni.commitstew.com`) || Host(`nwinter.commitstew.com`) || Host(`alys.commitstew.com`) || Host(`dan.commitstew.com`) || Host(`xenocid.commitstew.com`) || Host(`jordan.commitstew.com`) || Host(`alys.commitstew.com`) || Host(`dan.commitstew.com`) || Host(`xenocid.commitstew.com`) || Host(`jordan.commitstew.com`) || Host(`brian.commitstew.com`) || Host(`nick.commitstew.com`) || Host(`alex.commitstew.com`) || Host(`clarissa.commitstew.com`) || Host(`luke.commitstew.com`) || Host(`mike.commitstew.com`) || Host(`max.commitstew.com`) || Host(`jay.commitstew.com`) || Host(`sergii.commitstew.com`) || Host(`cole.commitstew.com`) || Host(`forrest.commitstew.com`) || Host(`chris.commitstew.com`) || Host(`echodaniel.commitstew.com`) || Host(`edyson.commitstew.com`) || Host(`clive.commitstew.com`) || Host(`byorgey.commitstew.com`) || Host(`kim.commitstew.com`) || Host(`kb.commitstew.com`) || Host(`kevin.commitstew.com`) || Host(`mbork.commitstew.com`) || Host(`shanaqui.commitstew.com`) || Host(`philip.commitstew.com`) || Host(`bee.commitstew.com`) || Host(`adam.commitstew.com`) || Host(`mary.commitstew.com`) || Host(`martin.commitstew.com`) || Host(`dreev.commitstew.com`) || Host(`aian.commitstew.com`) || Host(`commitstew.com`)
#     kind: Rule
#     services:
#     - name: commitsto-staging-x-commitsto-staging-x-hephy-stg
#       namespace: vcluster-hephy-stg-turkey-local
#       port: 80
#   tls:
#     certResolver: myresolver
