---
apiVersion: traefik.io/v1
kind: IngressRoute
metadata:
  name: kingdonb-dev-insecure
  namespace: traefik-production
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`kingdonb.dev`)
    kind: Rule
    services:
    - name: commitsto-alpha-x-commitsto-alpha-x-hephy-stg
      namespace: vcluster-hephy-stg-turkey-local
      port: 80
  - match: Host(`kb.kingdonb.dev`)
    kind: Rule
    services:
    - name: commitsto-alpha-x-commitsto-alpha-x-hephy-stg
      namespace: vcluster-hephy-stg-turkey-local
      port: 80
---
apiVersion: traefik.io/v1
kind: IngressRoute
metadata:
  name: kingdonb-dev
  namespace: traefik-production
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kingdonb.dev`)
    kind: Rule
    services:
    - name: commitsto-alpha-x-commitsto-alpha-x-hephy-stg
      namespace: vcluster-hephy-stg-turkey-local
      port: 80
  - match: Host(`kb.kingdonb.dev`)
    kind: Rule
    services:
    - name: commitsto-alpha-x-commitsto-alpha-x-hephy-stg
      namespace: vcluster-hephy-stg-turkey-local
      port: 80
  tls:
    certResolver: myresolver
