---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo-insecure
  namespace: traefik-production
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`podinfo.howard.moomboo.space`)
    kind: Rule
    services:
    - kind: Service
      name: frontend-x-podinfo-flux-oci-x-cluster-02-x-default-x-64cb0c2df7
      namespace: vcluster-howard-moomboo-space
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo
  namespace: traefik-production
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`podinfo.howard.moomboo.space`)
    kind: Rule
    services:
    - kind: Service
      name: frontend-x-podinfo-flux-oci-x-cluster-02-x-default-x-64cb0c2df7
      namespace: vcluster-howard-moomboo-space
      port: 80
  tls:
    certResolver: myresolver
