namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.10.2

configMapGenerator:
- name: config
  files:
    - configs/config

generatorOptions:
  disableNameSuffixHash: true
