---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 30m0s
  ref:
    branch: ksm-dashboard
  url: https://github.com/fluxcd/flux2
