apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '^4.4.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    tcp:
      "2222": "vcluster-hephy-stg-turkey-local/deis-builder-x-deis-x-hephy-stg:2222"
    controller:
      metrics:
        enabled: "true"
        serviceMonitor:
          enabled: "true"
          namespace: monitoring
          namespaceSelector:
            matchNames:
              - ingress-nginx
          additionalLabels:
            release: kube-prometheus-stack
      hostNetwork: false
      useHostPort: false
      extraArgs:
        enable-ssl-passthrough: ""
      kind: Deployment
      service:
        type: LoadBalancer
        loadBalancerIP: 10.17.12.206
        nodePorts:
          http: 32082
          https: 32443
