apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '3.31.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    tcp:
      "2222": "deis/deis-builder:2222"
    controller:
      hostNetwork: false
      useHostPort: false
      extraArgs:
        enable-ssl-passthrough: ""
      kind: Deployment
      service:
        type: LoadBalancer
        nodePorts:
          http: 32082
          https: 32443
