apiVersion: v1
kind: Service
metadata:
  name: db-deis-hephy-workflow-lb
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - name: primary
    port: 5432
    protocol: TCP
    targetPort: db
  selector:
    app.kubernetes.io/instance: deis-hephy-workflow
