apiVersion: v1
kind: Service
metadata:
  name: db-kuby-test-production-lb
  namespace: kubedb-system
spec:
  type: LoadBalancer
  loadBalancerIP: 10.17.12.226
  ports:
  - name: primary
    port: 5432
    protocol: TCP
    targetPort: db
  selector:
    app.kubernetes.io/instance: kuby-test-production
