apiVersion: v1
kind: Service
metadata:
  name: db-temp-store-lb
  namespace: demo
spec:
  type: LoadBalancer
  loadBalancerIP: 10.17.12.240 # store-db.turkey.local
  ports:
  - name: primary
    port: 5432
    protocol: TCP
    targetPort: db
  selector:
    app.kubernetes.io/instance: temp-store
