apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../base/local-path-mariadb/etcd-mixed-arch-k3s-mariadb.yaml
patchesStrategicMerge:
  - etcd-mariadb-k3s-patch.yaml
