apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  #namespace: kubedb-system
resources:
  - ../base/local-path-mariadb/etcd-mixed-arch-k3s-mariadb.yaml
  - etcd-mixed-arch-k3s-lb.yaml
  - ../base/local-path-mariadb/keycloak-hephy-pro-mariadb.yaml
  - db-keycloak-hephy-pro-lb.yaml
  - ../base/local-path-postgres/kuby-test-production-postgres.yaml
  - db-kuby-test-production-lb.yaml
  - ../base/local-path-postgres/planet-store-production-postgres.yaml
  - db-planet-store-production-lb.yaml
  - demo.yaml
  - ../base/local-path-postgres/deis-hephy-workflow-postgres.yaml
  - db-deis-hephy-workflow-lb.yaml
patchesStrategicMerge:
  - etcd-mariadb-k3s-patch.yaml
  - keycloak-hephy-pro-patch.yaml
  - deis-hephy-workflow-patch.yaml
