apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m
  url: https://github.com/kingdonb/csh-flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: wordpress
  namespace: wordpress
spec:
#  serviceAccountName: dev-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: wordpress
  prune: true
  validation: client
  path: ~
