---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: any-old-app-deploy
  namespace: yebyen-okd4
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: any-old-app-deploy
  validation: server
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
