apiVersion: kubedb.com/v1alpha2
kind: MariaDB
metadata:
  name: keycloak-hephy-pro
  namespace: kubedb-system
spec:
  version: "10.5.8"
  storageType: Durable
  storage:
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
