apiVersion: v1
kind: Secret
metadata:
    name: kubedb-community-license
    namespace: kubedb-system
data:
    license: ENC[AES256_GCM,data:8mU1s1Otc1jfJX2FBCRKi1FLINH8rBwlaAkfdOrmhVADyIge0Q5orS8j7TeZweVN5PATmA2g5N1f0BURJzDMnTiVKm9gO40xp+zkl9yVpWxlov/NaywSev8RDIbq+1sUOwPQ55g2nm/06oInB5F9M4V7tOBg9+lJH1/yb0NQf3kKsIlv0JBVXNZ8j0TUtA8ogaunqdKvQb0BlDbVv/bDp36/Bkfs89JVyKgqPDhWmt64RJcnwWKDnH+vRmGPsR7QoDHZ/C4SfQdckQUL154veZUIKGDN5OdtcGMv0kildEX4v/6jkeiy1nmydZ5/w7scBOPItx7t1yRQ4qNruRDgq5LS7GWVdxkzXpIHqK7ubxMizkF31SSlGfeYKIl76VvvCTQkk+01MBkT5OKuhnbnrgWoQJY2Rd1beaHxtJ342AX5yyZN+Z99kyQSp5f5DpoEtPN0PtZT6xZNhFUTpmEfe0lHofaJUIYQjjO0lhiOLtCkqJdP82M2+oAMxTa4EezS6MCoz96TgYpKC8eTA5lSWI06DMUFuPsdrETCio5u34BnalyBeaQMRsxZIKJjuKIC2lJbaFHIQHPtvyB3tSXChFqyCVTCZWYKs0Ug2FIe2bMyv0asgFevmD9S/XkQG7HradsenjcMtyWWknUtYvVDGCLvYF0CyondgWq+wgv9aB2OJ7KYD1fzAvfHmn3dGqDWSvX59PFwOgcA7UAZ0sMBLlwdEFdpaPfa4eYDnU6wduPbnVGTWtbJCkduEF20K4PGunklDmjgBWhqNjaukUBx8j6wZ3xR7shkGrPet0gionwlrDLRsR6aOnZVeQEfjTuB0U9l8184ylEwv6MDA+GyWzG+nKDzvbyaQEoovY2n9UxFNDEqTVKx3KN2wwG5SE7kVJOFCf97gN46SwHu79aMzNZRz2o2E1J5YEfVO1TyCLjShbm4FCXpxuF90eArqpY2MzK3c6dSWy9vjnXMSOLR7iqIMiBF1o3KgUX1LnRMo6foaEU/ParkqdUKumtf/rl7cyt0Qi2AwhesJNUjYB33T/DRl0DANG0ribKrnNWNo+PLHXodv6B6u1+BliDkSnq0FJFFf+2NVtqJfsPviD+R6tJKhgBoe+CtjzLmeGM0L7My8koRUV+wegfo1BNLn3U9ReH7s5cjU/e1JqdKmY7phipBK57oPt1L0zy7UMoABfodenZiGm5Xw+B6h5XYZt0VDzjTXI6wSk9D6OsByeIrMJXztOvxN5m91uUGNOsrNAPWduKkWNWFpPcTvjA/s6Q5OFRYJZ0FqkyPEN6QCbDvH7USpk9YiBgfpXxcZoTAOW2DtY7yKBqUUmxwwnCtyZAs/EcuyEMVIvuES3oJtnaUea9gJbBOBEqUyxmoPcQrX2FR5ZW8AHlLeepgMHjWJK7oolewftNxHlgPGXmfd22n0uNgiFa0YC2sIzuAq9McJsf4+6Qd3WqsfOvKZwBCZcbXguEbB+50WepSjftZRJziP6BM7IlDwKinnXV5gQn8uTD/57elD/OoJqEw4aEGl3bW9QnHxxRh6UtJDo1I5Fj7AkWe82pSSK4sWxe8CLy7WxNH0P45XqtmG2/H53EgnL0waE4V01ccxfRuHp1dcaIwB3t3LNLifvhyiaIedNU7qw8xKPEbbrIJAaDfl3zb+i4cENH6rRmbxCgQgaiCT+9Pvh+EvMMMVaVIIYDslmS0cJ9f+EVBTaTfK+EmVOI71HDEh1zuesaFw+WvpKAfODKqUTuJdW8UOwCCB6Oeuis97CSu0m/B2t0HjvIWhFVM/XIdpD7Bw7Sh6e/zffLirKMQJ5YetlEovM1GybfAQz/Avt432FeE8xUG52NzKf4iCVXZz8oNfCOfIpkvtCuQ03t3b3Cp9picn7GhIuiGhcyZuxhEyOrkIoxjGzL2K8dsqFck6e8lhDaRyVpWFQT4UW7g2jPhiP+OdBQsmD7bT5rqksSSgLLCOfEmeO3PMK4SFw/sZiY/H+b/1aL7NLtALPaQo7yog68u0o8zbNvGSdiDUCet8ERj4lmjROtwaXCYabllgk9SwopEba0rkthHk4SJ4XDUrcmoK3qLLYtEXcSdaJc3zMwdNrxVqNyp4fpjgzVQM20tgDLuXlGY3WOEWRgDHNfoUH07MPrBa81Uv3tLLMilQ9EpKMD+MLbgPjVmioV5/NGygWJNWlLrp3jbpg7xy0GpNer1CQnbFpekI5YGeUgbEYbjBx8mC7hsLq75YvmdE82j4Oizp/OsvfTGI01X0YckmNfFnbSe2/Yxqr4ooXR93YE1fh2CwL+TYfwg7YvCGNVCV4sxZK4sVb+uvNNs4X0nB1nbXAObNA535yaYC/b9l1TW1jbzK34tI0un3aj/rNCeqVXZGuI7lelh6eprjA==,iv:K+I588XpNBmPuPzeYB5qKClJeYoh1NzEQSd3Nm7nTVY=,tag:isjYr7W6kjRIS1HIL6PbsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-09T00:12:32Z"
    mac: ENC[AES256_GCM,data:lT6HJEKwOw1XbmjWUqRsPFzFU1iMbDS9R6GNN5npU+x9G5nvIqqGPt8rnZz1wexThpsh8n0/3swR6ioSibQLpBGukCAnMFGiyvqSPl9Xf37blrqjycDSHUjVw9IqTSETEJjc4nQnTqzrPs7tHexUUVvMnEBnISrUMBvY32hbz4A=,iv:IkmUOSUlh08HOkHzWkhnol7sWjvQHM8qleeeDOACy/c=,tag:9PAtwtENcpWEAXERdY32cg==,type:str]
    pgp:
        - created_at: "2021-07-09T00:12:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxokV8Msv/eoAQ/+KaAOnGsEBvSnj2hjOqMj5GRodZ6A40vs2Zrf462Rf8VH
            10nwCnzQDu7xIBy2E2g3B006xFhhsOOKPsbC0cgyxPxiVJ+6Puu0AilkF93QbSiR
            ENwMSHXYdK4962Hg/CKdoSm9e/i6VEUQ4+L/Vj+d/0UaWC96BjBHarCdDneSopo8
            lHJmkHig+vDxRIlsspq0KOsFujsOI/aIP0t8gjOc2rJLxavU/jxYZV5gjRbJvQLO
            S5kllq+04wRAjZZpvInccVFWuJ8guy323AfWcq/XoVGK50xwYtIW2mcgDtz53ZCe
            e3T5MfyJBstBU6D1QYHD+SgwLjgug8JIVaQT2ff5mzEfD+iDyHORe/L1sTxPBV67
            RPuM67YvduyIVIoYuuj3S0ydnHe9dNDHOAD+4XzeVePN2ZNUhXDZ0rlTgJTddhHI
            eXu3Qgq7ykzfkchDmuT0NU4knq4US1YoLk3phsj+p581kUdo/6ownDEfN3jwH9l1
            KyKoFlwI34iIPgnwGOxSF+IPiHzkG1vhW+xoDIlJLqEX0yeIRBizJRJkktore3fZ
            /Vszv/FLrsaDe9vTyZP7rMXyzCLJSHOhiAr5RxZfTthHpxqQEIe7mfqqmmTm/ckC
            Wt92pwsntHYc1iDywVTqF9zLCqMx02SFz98oXIcpCNsIgI9i1ONzU1MuThZWa+HU
            aAEJAhWQWEGMn4LytPwgL+QYwXQGQu2URYOiGDy9z7ebXToeSuSOnVLy5hwnxesM
            Gdf1pl8DcXefz3eyaodLYhNI+aDVlUIflT7gm4D+2AeOZUu1frKSg1R+JlXdwCLU
            yCEqgEBdyeFI
            =zRsh
            -----END PGP MESSAGE-----
          fp: E0BFF42212EEFC20B5547D619BFE162D23F11BA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
