apiVersion: v1
kind: Secret
metadata:
    name: kubedb-community-license
    namespace: kubedb-system
data:
    values.yaml: ENC[AES256_GCM,data:jVwgrWvSMDcy9s6ykP4eWmabWhDHowtcv30tFprEkOdCXOvDavvtjjIODj0Vq09pA1fpaaGlKadmct2pdywlRfp5f2RmpokdBZEd70Wan9rHPOY4TWNel91/5Ak5WVge0npb4kynL4KXvWGlsKn61SNVzVAFMZvtjH5kIH6oi6uoa7zgzeFNadYFJBNYT1dMm01aKnh4ccOc09hzHQ0sV8oY4nvfYGnP+6FCeKW/ystcTJmsXQXdwssdaFCo/Tgr1+Up6jqYvb38aFqvl95Mzxdv56/+MWznOTnpkbqRj5CC3syLVd2/W1C4FYCgHSMMmlicVI/UmKUe99pL/HVTdFabruw9VIRNZGqpk9gSgEoawcONAHBRQSR3oTXm3mONtXhq1xZvir+oObrreKQtuzYCZbljn72sRLIJjnLYTuC+HkHyfGFKTc095rROz6JDm5rzo3HtlGW1D/FOQhsxtJa7Vo9Oe4J5jgZKUd+Eo/H/6akUa926Fho0YKQhrwBXeLALxPHtqyEKN/GNvxrgLco6iytZw7napde7UtrGjT+H+I47OEpTX8iuC6bD6jO+hDxigzVdGs+n+2NlSC4TzxakGKEpmB2fb7bqqBZ6sWG8OjBG9l5vqMAwwr9INCbCPW5MGhWyMjCdo9gfPurXUiKPWNG/i8OwWPEjGgdqL0Cx8zQChdR+x6BN2N8vX2JqcPzAwgEcPtdm9wLooj5c5pPGfzAIWY0GIwZZi2khayQKkymkagRQZRjyo6Iq2o7cx5CgImpZ9r6J3tKzYHbIkHxulgSHA9ZCN3TmLtxHnE6CrkQOMC8g0KMoQVbDXgwQ354qMRpE94Gfc16/FU/Hvw5Yaev4UmnZ3+rWCGh5lfdvxKnefTtVYyZuPEm1ya8Q82lDUbMz5RPsaddyjPq88VkmJsyj8g5uLM49lgGtvMMd8+mefRwUose5s22ylIY66Bquqn3n6JgmDV9iInwc59oA8JuIocQjKNecLn8xxGydqCxk9XGOzEfvomSouLpmNlO5uozRyv7dv0rogyPzNmzb85oWm6OAabRidwAssOjdL72QZh6ivtgNprG/zQnrTQtxhJT4XrGZn13GIKf5gGy9dJ7sC3C3AYTyhi/rU+qnf84qMMvKVEz2ynU8OOvRbr/lQ1KtBzUSMmYBmmi5f192kbj+213PpLDw5S8GsCRxzKzUZZaoCUc8LmK7lpBT666S0yVih630aPvEmPFJnhIh71J7s297lCj/19MLMPk3+RVfjE+IWZH+1HGK+7UcWJ+BzFgU7uncZzh7vhsaRnGnmI2RlTzazyqXQY13GPgVIyyo9QRT1QKTkhweTAcZrhRp4RnszXHcgTkBCUXGx8toc5UxUq4R0UZMw79m4f2KdlBrpeNqW2mEtL9YqhohPgFBDLapAi1K1QUMGbOWnWQVWbYv6AtDMOfODPS50MPh3ootgNqCVP1a3ReUbK/9lyniiKW97CKnwwDy019ft0OHLoaroJ0cHEbhQ/qMkyjDuWqXZh1IISCQx/2lKbjB5t56Sz+HspQQBRi/lUCTFSkaEzrk61zraMAHysOgIj9Ftt3/bOAFegxSkiY8f5WqnGRl8ibw3XjU2tSpLPup0YOSoi2FzKreE2+v7qCPxhj+X/fm1SwEXz1A8EdSjHZ+k6NPJCWTq8csqutRDA/IliTL/BkfcbinfYj38hz9ERWE34rrx7XpB8nlDQNsXGqBxOXGDsjeWHYGyzPkVdqTziJKhs+5Bbi2t/0ONgx/97WzmnPk1HpsRD+KrBc9VjB80F8JU52rMXdJombWe0kb1+bhgrow8qyM4ngFbLk6fRFXs3HIUAK1g8oCJrsfjikFrPA7tz0Tz9adNxNbIRlhOOev0ESaqJzlijIx9jsoqkL3svv6USd00xWhQ2NwH5PByYvCkbVQ5fh3LivCiCcrEOCMjlpqvfybdph3bvDTNPlaskOfFMV2v03azR275yTtXxom91+4JMt1Pkr4AtYpKW78r3gtaheNbtUihX2ha2FUk2y8FgR06GvapepYHD3/8aWiLF6yOK7V0LGQo1fBAkeSFlefauiCKNvLFETh2u7K5e/GAQfhK4VitLM87UogpyVCqe4gaVXEe9x6rez+osFo7l9M9SSQIHlBWbd+hYJMC3wEH/sTMVW5/cgR7RWFZk+4atHSEwtNBQL6mABUzBcZ5GfyyWjfCQyHi65P00dc/460SHqTWrfeziNKy9DJEdFb+dUiUisi1R6HEjPIV97CY7tIuBhdlrvWgkcOEDqspQB3UJSwyregjFn0MX2sc2ECJFo994W+EbQLBylxYgDVTeFmxhx8NeltuYNxyVz5DTLUFdEhDc0W/POzHFq+RloQuVg5Wi6CCURCiXqcCqJYL1TEQNrUgkcT4X2lYvPiZQE=,iv:l+v0B4A8bqNRcFi4xfzNQXtZeLSG1SRuJFufKUDPK0g=,tag:MPtq0fqA7o1J7NVvCVHoyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-09T00:33:54Z"
    mac: ENC[AES256_GCM,data:DEt5ULC3Iy2rtSSzwYRF2Ysp7uAzFrIk4OlnFlgnYitHCWFnJOiKn1C0jbZdLTfalQnO9EEADPGp2TkWC/SvFq2h9taqESOrYZDrO/UA0QTTNZAt+mxwe5C9+1KclCB5z3ZK5jKMrIU5C3nY4VyeJDJefEZvhf3nABqKXZolHG0=,iv:X3QXpabLQoD3590XlAq/BAhL3bawb8wf5vKchotB/rI=,tag:gH2Jmo005BxLPIo41aiMxA==,type:str]
    pgp:
        - created_at: "2021-07-09T00:12:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxokV8Msv/eoAQ/+KaAOnGsEBvSnj2hjOqMj5GRodZ6A40vs2Zrf462Rf8VH
            10nwCnzQDu7xIBy2E2g3B006xFhhsOOKPsbC0cgyxPxiVJ+6Puu0AilkF93QbSiR
            ENwMSHXYdK4962Hg/CKdoSm9e/i6VEUQ4+L/Vj+d/0UaWC96BjBHarCdDneSopo8
            lHJmkHig+vDxRIlsspq0KOsFujsOI/aIP0t8gjOc2rJLxavU/jxYZV5gjRbJvQLO
            S5kllq+04wRAjZZpvInccVFWuJ8guy323AfWcq/XoVGK50xwYtIW2mcgDtz53ZCe
            e3T5MfyJBstBU6D1QYHD+SgwLjgug8JIVaQT2ff5mzEfD+iDyHORe/L1sTxPBV67
            RPuM67YvduyIVIoYuuj3S0ydnHe9dNDHOAD+4XzeVePN2ZNUhXDZ0rlTgJTddhHI
            eXu3Qgq7ykzfkchDmuT0NU4knq4US1YoLk3phsj+p581kUdo/6ownDEfN3jwH9l1
            KyKoFlwI34iIPgnwGOxSF+IPiHzkG1vhW+xoDIlJLqEX0yeIRBizJRJkktore3fZ
            /Vszv/FLrsaDe9vTyZP7rMXyzCLJSHOhiAr5RxZfTthHpxqQEIe7mfqqmmTm/ckC
            Wt92pwsntHYc1iDywVTqF9zLCqMx02SFz98oXIcpCNsIgI9i1ONzU1MuThZWa+HU
            aAEJAhWQWEGMn4LytPwgL+QYwXQGQu2URYOiGDy9z7ebXToeSuSOnVLy5hwnxesM
            Gdf1pl8DcXefz3eyaodLYhNI+aDVlUIflT7gm4D+2AeOZUu1frKSg1R+JlXdwCLU
            yCEqgEBdyeFI
            =zRsh
            -----END PGP MESSAGE-----
          fp: E0BFF42212EEFC20B5547D619BFE162D23F11BA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
