apiVersion: v1
kind: Secret
metadata:
    name: kubedb-enterprise-license
    namespace: kubedb-system
data:
    license: ENC[AES256_GCM,data:pGEZ2CyGY3wMC1dp/RyiZcXHmefelOwdSGe6YIndF1Zdap7hPzkirUHW2X+u7IuBCDD6g/fa/mUe6+Q75fmM8cuX4zXHHQ2eGzRfrSv2oVVwbz1isc5Pk8+u/ACvtjwAgS0IRerQP54J7nQUJHBZsqee6ctryjVEiKKtG9VyTGjsAipzuscrsXUUyKFSEFUNZwB88QR0jd8Gzj+crIvylqCQTOZ/OSs79vhwQXMlM58E8snqUARF7C1dtsols+dzyCuNYtslI8zp6PhEgxdMrBH6xEx2sUss181eT6dNzGyxuzsftwO8X/LhsDSLBzSANTx5KruBafTfWSoT7FUisfsT1l33NcBCqYtS2om0jx+EWtcpdbr9i7lccEuNbrb9OhQom249y/wbjCyNS4JR5OKQwDrhaZKfEhCryVWYiYxjq1Mts5QThchIv9qxHCfK4NPVC//UidbDaWeqIWdoHWo1P+CTGMQfHYuxT0y4wqUkoYHdblfkjyanktz7fhkszqwQNFQb45zHjmi2cSxDD/8UF3tzEJFZzgZFbXZd+iXBXzF4GLHuaQbhDZPIwDFoMtPLpp7L2DANEqRarkO/VCqLQ2K6lMvw6tesEQxekwK78u3iLSEkDE5V35mLYff5Hx9n+gka7sxh8z/aZuX+kz/1RwsFnYa5JCOvkGYYH3j8mY8E44tBz5Y52ImASeSxCb0++PA6DFkHQtvMMfRHbEL4WqebeuGut2Zqmd0z5j6oTD9UZOGDt0s0ReDNKujKmD/bjzCbx8glmWsVp47X6q2M7KGDZBAoT8U3e30C1+pZ9lQb+6xgmDQPYoywsp/HZ2xPsW0QLr8u1r/snlPeqsQxROa4vwy2AmGBFOmt3x5WpMhScQNmV+U9Nvcm/F7f0dghnhfIV8iOUnFCukAmH23c9UQkGGAqIplz7xd6amIuXXoONMkt25/fOrvxgXIOjXcefIdJiaBaPsFGJZYQWX4GLQJl1MkBGxCq26OfvJCLinJ3+3N2ZFmqCOqIenxTQiJsr9qfkSg7DD2mZklRLTf4dzLuAkZ/kbIYInFvnVo99jL8aAofLlSpOGCyHMAT4BeAm17plhpQBlCoisoGVN2Mgi0S0bKUBWyZglg7Qnt0SgkBB2WN+brcnH43EBieTyBX82+6qzGr055yt3Zvr2OorPEO4CqV3hsYiJAe5QLdKWz2Wnhm5qXMPGDvCnToW/fdwZSuI6ZnPAhtvylZhCN6s7xWo1lTzsTeONh1X3VoJLMHu+QWO2AN2REXzdstSMTdx0W1fNiUTfjBYF3+JztdBsptgSVVQHVTXQKra6Et1H9g3IXom+SYDhQUtEUWM9cHXoKRb92VZqeafbbj+hanoOwTOQktZpnjnvv++8QJmYzMDqThsZ2fF2sUZBo5Ls4SzcRzqS1xx/IguC9fCdiSqfZV/+kQEk0kUkKPInG6ImwKjUU9fZaoUFpWph53b3bxPLSPVfm40qFw62WaUKPW/VG9OV9tg9TqFldU79NUDgI0ez6wjiH/EjF8Bgo3rJY257MOlol9Vn1OnJP7eFhwFdEWgJkrF2Lq7tab4z9gdWf+4JNfJB83hjcgZBzYFPbPxX9mD1+hzoqFwqVMLk+ZtN2L/Tp8WGmp2NC2aWCj3kOQPhhixQeMp14exzVwQyIfxoKy0QTlJvJMzqgWIQ/cJfqTmKuCU8QrYREaqbkeHqvFe7uwFNEw42YrQ9l92reKMrYvI9pa/K45w5nmskPkfbJFgzUqIToPIbht8KzecexlYWzuEA/gaJsRt7QNYmfCmiuBqDqpdunKuAzFvRAf9Tj0FQ/zo7L3N0ztMc68MNe7EwMNWqCKk9Kk9BEFwaTsYtbBfYk82tLAxdLz7vzYjMzVrpPGlkV8yIDdJoVEw1hdKjxhvDtJuVLnOp8E5TjQZeyk0cQFd+sJKF8pL5YBMwNHm6c+OEjWfEPobTCZDZjS5seI2OJ329b+ZSpKmZ24mO09TeXoNUPTG2FFXQxThhW7CD450e5qgc4+dBj5fp5v9kGkJRtQ9MEQa1PI8ZtwkiqKfp2GwXGN9xCbImqTz0e5iVZQ7MSqjnGxig7LhODSPwKeeWzZgRt9jYh/v/9Nlm7KhzIRrYKELCoPLL/5pKdFxsSTphGrepFWAX6QRjik7qCAwPkOlSfAeNykP6IxcaChvmb9WYLPGITW0AuLkjlIwvlTq9IFqfWr4Y0WITpH8lKOQTkmcwVR8aIBxT42MI9sNzwKGSvETw8l9cSKyk16DnDeeF6BrfDYrcgDKWSkt5E/REZSwO5K+GZlyb5mxDDKa3WdF1mrouOTcHne1YAXOOtmyd2z5thARjvkr6jH8tH9UWU9fw/230DgJmCqGxLyoMn9vzhkSiV82tMMIRZ1+YvTldMMApJUUiBfrlZTigK+zK3rdWMcfs2hcnh7IohrBIpvJfv3PrVnQLxNirT/xYD9WBdiPubJkBm2LvsY7HYVc04bkLAFO2MFhHawfB9/njp4zPX1pWTkR03O43mt+lugdswTMIqT7sO0Z+CbTi2QFXoF+OE8igOOOJkXGeJ3r642vvioLpjRDhGJpkwDve0xmy9O1aTob6NfxWjaKrd8pzxFUfVtIor3gJ986Me4FUx9NVYMbueaakOwYXGHmjVGvJqCLB+4khsTh+8MfvCrAonCQiAPDC07tCID6t9VACedyyzz1vd+EVzYLqW36zl5YmFjPMKcSL1nbrX9L5Ca90nsPw1KhbhqCUGNBDn5Bm3vTJW+5B8KoysMQyXhPlID3s5fLm84GJLCJsni,iv:jJ9T0KvjvU22GnMs2oFkjtfcvBP48x0BBIU1995RN/o=,tag:rivoEz/h68cMhGaPGwGwjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-23T00:30:43Z"
    mac: ENC[AES256_GCM,data:8cmg54qW6FCs7ukW/fVMTapmFtavRGcmv9GEYjLN0aRku0NNUF5l0U830nOqTuZo3LuQ1shcPe4GCI3Hhb2nAbZhryYoMS12yWj6Z8PYqCigCp8srA5ZGqX2LDPg2ANROTflI68oEa/g7leo/S87TQ8c0drbIkebtDd1c3nuU04=,iv:wR8rxxfMhjti2A4psbSmMJ51ejeuogdTTAAOfWjMP8I=,tag:sIQagKI2MxZaidKjUvk0Xw==,type:str]
    pgp:
        - created_at: "2021-09-23T13:29:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxokV8Msv/eoAQ/+MUGgVZF7eYcMhClabltQqos5NBLWrcPEZt7n+lMKJBYW
            3klr62RTNzv8jl4ScOBoBuvchyl0Q5Fg1ySJdZHjeMpiscjgShXfowE6ch2nfiLn
            vKS6saRII9FQT62QLY86sQTslGHPjJKms3/iHc/5lng5b6a0I5VjcTikxtxX4H7r
            1zDFV79kKo+zb5yuWxqfvl6hm3w2f6PzBVMYU5HZuOWWp0NUBvdskEE3wOGhPBO7
            cYd37RBFEwF6SFYP19tiPzZBOjNyfnWUTV2TzLoRc+QLkxG0yf/D4nTO8VEQJe6L
            NBFTgk8xxL9KC+lp78Dpx3d5l2vbgA9wdvI+60/RHJXpL2zbhVMwSZKW3qqCXBAn
            K0Pcs35OJEhtBsGnnU0p4uEMAZT7+k952llKyiKp5dentjZH8hzrhHY/AV04tlmE
            5B20E9h2O47wKcOrTDuz4ta0PbfinZjmZXa4xaZGlwLKtvbsH7vOBVRl0s0S4VFv
            mzMKY0Iw/zY/6RDd0FKtXRNqmD5z5Ypqbj75yrcR47B6hpB14kiL4EWTFOkejgsO
            T0eTJLkgZyK2nHzMU4CLxmHdw+qzdA4dIhkbdvDMZaWukLco518kx/R3BgAt/0kr
            khJsIvVBe8mPNlJWhVn+PbEKzWSzteGNL+OuGWE5MyoWBxKtVszrjNr4VmnborXU
            aAEJAhW2iciI+P9x3USBm1mxWcGH9xjuRBFiUD1qwuViI/2r7XRZQskj6VmibMMi
            juqQkOrKXYmYOZl1zANYBQiYdave6dMFbZsZsn9X8rFVDvhmnx6Ajqyk+0MRmiiI
            NXBVXt342BjO
            =Yyj9
            -----END PGP MESSAGE-----
          fp: E0BFF42212EEFC20B5547D619BFE162D23F11BA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
