---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb
  namespace: kubedb-system
spec:
  chart:
    spec:
      chart: kubedb
      version: v2021.06.23
      sourceRef:
        kind: HelmRepository
        name: appscode
  install: {}
  interval: 1m0s
  valuesFrom:
  - kind: Secret
    name: kubedb-community-license
    valuesKey: license
    optional: false

