---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb
  namespace: kubedb-system
spec:
  suspend: false
  chart:
    spec:
      chart: kubedb
      version: v2021.08.23
      sourceRef:
        kind: HelmRepository
        name: appscode
  install: {}
  interval: 1m0s
  values:
    # kubedb-community:
    #   enabled: false
    kubedb-enterprise:
      enabled: true
    kubedb-autoscaler:
      enabled: true
  valuesFrom:
  - kind: Secret
    name: kubedb-enterprise-license
    valuesKey: license
    targetPath: global.license
    optional: false

