apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - https://github.com/kubedb/installer/raw/v2021.09.09/crds/kubedb-catalog-crds.yaml
- appscode-helmrepo.yaml
- kubedb-helmrelease.yaml
- kubedb-system-namespace.yaml
- tenant-kustomization.yaml
- kubedb-chart-gitrepo.yaml
