---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubedb-tenant
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./tenants/home-workers/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

