---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-staging
resources:
  #- namespace.yaml
  - traefik-ingressclass.yaml
  - ../../base/traefik

patchesStrategicMerge:
  - traefik-patch.yaml
