apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginxes
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    path: ./apps/ingress-nginx
    repoURL: https://github.com/kingdonb/csh-flux
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
