apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-tenant
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  source:
    path: ./tenants/home-workers
    repoURL: https://github.com/kingdonb/csh-flux
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
