apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ./manifests/monitoring/loki-stack
    repoURL: https://github.com/kingdonb/flux2
    targetRevision: monitoring
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
