apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-api-crds
  namespace: argocd
spec:
  destination:
    namespace: flux-system
    server: https://kubernetes.default.svc
  source:
    path: ./
    repoURL: https://github.com/traefik/traefik-helm-chart.git
    targetRevision: v19.0.3
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
