apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helm-controller
        namespace: flux-system
      spec:
        template:
          spec:
            containers:
            - image: ghcr.io/fluxcd/helm-controller:rc-78f3ffb8
              name: manager
              args:
                - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
                - --watch-all-namespaces=true
                - --log-level=debug
                - --log-encoding=json
                - --enable-leader-election
                - --feature-gates=DetectDrift=True
    target:
      kind: Deployment
      name: "helm-controller"
patchesStrategicMerge:
# - gotk-patches.yaml
- |-
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-egress
    namespace: flux-system
  $patch: delete
- |-
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-scraping
    namespace: flux-system
  $patch: delete
- |-
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-webhooks
    namespace: flux-system
  $patch: delete
