apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: kured
  interval: 5m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/mixed-arch-k3s
  prune: true
  validation: client
