apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: deis-hephy-workflow
  namespace: demo
spec:
  version: "13.2-debian"
  storageType: Durable
  storage:
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
