---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: wordpress
spec:
  interval: 5m0s
  url: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami

