---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: wordpress
spec:
  # serviceAccountName: wordpress-sync
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  chart:
    spec:
      chart: wordpress
      version: '^10.6.9'
      sourceRef:
        kind: HelmRepository
        name: bitnami-old
  interval: 15m0s
  targetNamespace: wordpress
  releaseName: my-release
  valuesFrom:
  - kind: Secret
    name: my-release-passwords
    valuesKey: externalDatabasePassword
    targetPath: externalDatabase.password
    optional: false
  - kind: Secret
    name: my-release-passwords
    valuesKey: externalDatabaseHost
    targetPath: externalDatabase.host
    optional: false
  - kind: Secret
    name: my-release-passwords
    valuesKey: mariadbPassword
    targetPath: mariadb.auth.password
    optional: true
  - kind: Secret
    name: my-release-passwords
    valuesKey: mariadbRootPassword
    targetPath: mariadb.auth.rootPassword
    optional: true
  - kind: Secret
    name: my-release-passwords
    valuesKey: wordpressPassword
    targetPath: wordpressPassword
    optional: false
  values:
    global:
      storageClass: local-path
    ingress:
      certManager: false
      enabled: false
      hostname: hpworker-nginx.turkey.local
      # hostname: wp.philosophyaquatica.info
      # hostname: hpworker02.nerdland.local
      tls: false
    mariadb:
      enabled: false
    service:
      type: LoadBalancer
    wordpressSkipInstall: false
