---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: flux-system
spec:
  chart:
    spec:
      reconcileStrategy: Revision
      chart: kured
      sourceRef:
        kind: GitRepository
        name: kured-fork
      version: ^2.17.0
  interval: 30m0s
  releaseName: kured
  targetNamespace: kube-system
  values:
    metrics:
      create: true
      labels:
        release: kube-prometheus-stack
    updateStrategy: RollingUpdate
    configuration:
      period: 1h0m0s
#      rebootCommand: /bin/systemctl reboot
