---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
      version: '>2.x'
  interval: 30m0s
  releaseName: kured
  targetNamespace: kube-system
  values:
    metrics:
      create: true
      labels:
        release: kube-prometheus-stack
    updateStrategy: RollingUpdate
    configuration:
      period: 2m0s
#      rebootCommand: /bin/systemctl reboot
