---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
      version: 2.7.0
  interval: 30m0s
  releaseName: kured
  targetNamespace: kube-system
  values:
    metrics:
      create: true
    configuration:
      period: 0h0m30s
      rebootCommand: /bin/systemctl reboot
