apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:0trHGVuZY/yaxPY4daWm1CIjespRPEHHp68E9GZo6UWALBIfEmLf2YnEHajozqTDvvCP4+iwP+MchGO4piFAvUAg45Pn0Fl+5W/fpN0twOXrPW8x6Fd7LrwB1jOVjaKDP6qAzGpjmFnaO3kSiM1RXs4SiOwqJkdDOX5xa7Diqe0Q4jddAS3IfgV1lPRCO8mHRlxgNfjn5knCFhX2frY2xp+HrBBEyZKjq+jLwtCazgdCxRGB+lQrR/Zxz2ROpElZiX/Y5Hifq0QloRx4XW+yUJy37YKaPSm1gmGBU0dpDaw1mXziVbZ6v10j/CDbzDUinBwhL4+ALKHxrpUrzQ6C3jqRTLGfcHxBizdtikKxSvKaVXoS9t1V3QTm7sXYFbncDhjYK8JGxznkk9qNkiybcSJSC81i2v4UhlqRGYkgRrac9bd4G6p7qgJq7tdgOJYkEiBFo3BGPyf210GCe002B5s2jvWVoekAdphM3Kb43jMANmbjPqdg0V+jvxJ6rcIW61yldtbBomttis9driAWsQjA0wTeELP7qcUwUelK2JyhSJHulTY8kvgvg96/mc86jdAnH8T6neSMTftSkHgZWSAxxkKfBN5LG+mUKqu1bgbDdbD/uxkz5YOoX7oeYBQ+uUMc2dq75CNzhTjFbK2c5oiC/hirqc99lVOZrMzI2RI=,iv:nftfLIk/tMf1JdEUUfV6ELI5L8sPyY+zbGJ8RuYjyZI=,tag:awITibXgGHysv0pOwsxqcg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vmnI/2xjH7gu34eAyGoSHca2PjstNHBqtYZOF7kWA85vTmpe4+qkoMFgXsFJcIw2SW2XwGiWPGWFAsDGb8qlh/TtjHGG6Ok0r9QZcjYohuBoyDEpfdxpk3MFOpMen5TjXf9STiMMGEWbA+mdvB0KH+5cNQ3PoYq3nde/Xs5c6yyv8Bt0zvbP2AhDDIlaPCveA48biTMtV8MRqKcrj8gIHQXI5KZOFVPFLR9AQyeQ65L5wlBHPJGcXruSvo3xaO8oLXx2NYnmX8fjHQIGtRJCyrWJFpdy8F3dVFSTxJdB1YXrrF0k8aOldxu+TKralzXjJqNlzmPvRZjJDGiqgRytTYsGcaW80gxZ4nUukgUKrOY6ctcxmY1XSZfVfGCeLmCZWsjUUNrlCjNVs0PatoFsskrVlxESn2xJJyrhwAZqQwSinvuKths3RaGvPZJQPi32AggtmA==,iv:T2EYa9uVsGeuV0i2PH+UWg4wWETy83dKAJ9ueH5chTU=,tag:7WFhgufDIcW+xqrcYaMojA==,type:str]
    known_hosts: ENC[AES256_GCM,data:dSrrVHATK+TPOEoAgT4F5QPYLDhEC54+XBJhIzXRf5CKGy5b28a+f8ZdFh58BtBylhZGexD/wXwRXiUWwHU1hmjk1Fz0AraEGq/mlKBRCZS9DNQmORJGexJRCrexRnaS/qdoe1LdQbSmUSqBTJOaHeqifLKU7bpj/P2EX6Vr+e7ZJlPh0vGSZR9RQ5bW9Sl7ZeYkwd2OytbULeCNC6ggHIcQ57QPrjagKxWE0hhhoRyYo4NtezTFg+QK+WLzUHjo1UzE4ICzSebQsKHmxMoNHYGBMjzYkyVntQko/vI4q0XGMGjcN34zRkpOfzdQtFEXUELHl8SQaYDbKD6gq8Ec0Q7KY4C1onFGhYS+BolNWI9UEcOec2mLbiBwpkdYWf/o9Yj1NhrmXXDvL6ZCPIUpiOYHG4+7LbDxgdPWhPNyzu56yIqPb8NrQ/1p26UIJSNlpgp/uG474hSTpX9IwO/j54HeCk7RrACCe9uu8oDRBE3wHR5GcSuXLYQ9B4eavTKhmyRUSAU0sZVVNm3ulr3eA67NBYS97VVI5j88+uhS/tY/+upX01Wsf1jDhN7DcoSI3RoHfZMyKWWQZOJFPv/7NZN50cDNcW2xVdHSVXdDBXD7s/Kf7Mj+IGoS19HkfjsODL0q5t62xDQcXxph/erLCoRIaNA72PJjzGGPHY1AR9JCCnSiMt3Ng5ieADc=,iv:ag1LKEvtdz/mnH2TFaPNpbvUGbEaaa/P1tU9q23IbRE=,tag:b6klzbbqHp1Td3S7c1WR/Q==,type:str]
kind: Secret
metadata:
    name: flux-secret
    namespace: yebyen-okd4
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-02T04:30:46Z"
    mac: ENC[AES256_GCM,data:fRJozbmz+dlHJa1m53MtIXpnU7rTUMwiHjbKSZTQoENubF12jZgFBdMsFkYVa1WhH/VCoT4wyXSuaS8RndHEoSJhuwIDy0uWtldG1pYy/3WU3az35nKtzU8m0AxZNMKpugOR9UZjektEeJzCcZyLyHrE/0/na3sOTRJe2aOExoQ=,iv:dQ1VYY/cojUAaTEpk0Z2CL65Lz3zUIFF3LsnswlXiQ8=,tag:lej1bKfoolu4cteHZ2Jx2g==,type:str]
    pgp:
        - created_at: "2021-04-02T04:30:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzitmgb4OwTUARAAsTFrGVKe+NoRz/w6K2Mt5YdyQPnN3FNDQ+t+nFJC9PWZ
            r2Bd1nHCxlniP8HukdWmuanNS2XuL14/aIukgVwxTZjsvhZModu8+Bc0pq88WFZ7
            wFUpjqKzKPvtln4dgm/6rk5uqQAEBS2CJpEOJB0D8EWhzGG2zMoflIvtqcY0gk4j
            iFc4Xrb4Koax6+qYHhmdy0tANvOVM7IlhZlv7p6cmZVUdh832pzNOxvRE9SOGkKN
            gBNmFgTWDRhOz8p1o2vJWxnyXNnKMT3CTYvxq2vVvQP+kGl+NS1XnYnaJWKKEQ+N
            qyfycXVANhM2b6V/WBR+9CJ5WdrdkBGrMqjnHo8O2gTzB3JSyLjWrrHb8CPRuStK
            rZuHluKfuJKsmzjA8MwKX9S8q7FmW+XYcNJRkE/06kU3dOVs2Tf8zOOFzun67QX4
            GDYP+jnQK/xj0HzOk0688qM9MXieRB9zmFJeJYUZcuRfkpQ2YyKZno+D96GB5iqL
            wfz+1H62ARG9URjFoY6Dtz8mrUcCRgxyGxZJnP4McB6Av/8LrAsRJAL/OmopWEtf
            9t35af/9Fyc9XobvyOOP1iJWBR0uNJI+Y4LF3ytHPhKDTv5X3H9BPW9/O/vhFdA3
            L44oiyGvg4eCbv93fCKPJu7vWBHSIWChyIkaRgxdQ1sLOTRjLzTbC+mUoq0Z5/7S
            XgETOglLF4hFOTkhwzvOnAeSqbRlEFhbFq8Efuy79+5IygFvKcAjHRWzUiJaQ+k7
            QS8mOEjx8C9mJpSyHnkX6V5Uc8rV7ervb2ODUs+2vbPiF89jem4LH3myphCcwAs=
            =84Ag
            -----END PGP MESSAGE-----
          fp: 504C9387CCDDB00E1142434ED53420A9231608D9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
