apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: yebyen-okd4
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: gitno.hephy.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: notification-webhook
          servicePort: 9292
