apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: csh-flux
  namespace: yebyen-okd4
spec:
  gitImplementation: go-git
  interval: 30m0s
  ref:
    branch: main
  secretRef:
    name: csh-flux
  timeout: 20s
  url: ssh://git@github.com/kingdonb/csh-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: csh-flux
  namespace: yebyen-okd4
spec:
  interval: 1h0m0s
  timeout: 30s
  retryInterval: 2m0s
  path: ./clusters/yebyen-okd4
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: csh-flux
#  validation: client
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-gpg
