apiVersion: v1
data:
    token: ENC[AES256_GCM,data:7++nyTz5D2Uhxur5lPnRwkQ6iz8YqVoHKSO2kIYkaxBiphno95NHIxWfr21n2fk9pFIK+4f2vBk=,iv:7Hr4Vuj7ss9z5y5Ame8TkSC1zBnN+L4ItMrjQgl7G2g=,tag:bOqIrTcIZbX+DN8Aoua7XQ==,type:str]
kind: Secret
metadata:
    name: webhook-token
    namespace: yebyen-okd4
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-11T19:15:38Z"
    mac: ENC[AES256_GCM,data:CaZ7Nfs4J72ROsYK7uPFGHwyZ7HFbLtwIg2l/w7LnS3NOBXLcZSWH7XUGSc+eo9h2ajunSyIburbM+Fhu/X33z9WxxOwyjmGBxSslo7hRl1512ZshsT3VzXLhed0mcrxnlH4aqAksXzMEHOrlyIogZzigUuqDSgGtZiNIrrNsCc=,iv:LaVgZkzwBlzv59G840CLcrzTMMy/12EiRmb/rceplAI=,tag:+i2ORGXQbF9tBEgoNQIqjg==,type:str]
    pgp:
        - created_at: "2021-11-11T19:15:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5OtjnaxAzRyAQ//eBW89b2kcaK+qAfQXcCmvEIr1xEU3XUNqjYQSYLBPEiy
            1gKY/IONgcQgSX37awCSKT0geOV+iItUXfgyZ60UvrgwnBt4EbMGDrBM6KD0r++P
            shblXY4FWBGCJg/0b2ylI2nGV29dweEqleVpnBfQCevw+gnSAPlKoe25JpI4Thk9
            LBhNzs4j9PDiHchh/uIvAlaPLeLYoUl3REkw2UGpAPW73f34UNBA/Y+ohBGSAFFA
            PH7cL0m5n4q25Y1v5wZfY4DMh2dVVKSIfHR2AtPMTElvXxX67ZeiZj9Q5ieUnFju
            rsSoj1LQ74ze6m6Uozz7QeGyfcdP6YCPRo0HDtOmZRJUpNSRYtY/MmOY1fb341A0
            p+vGjtg4T2D1AOImPVwQlNswrgcbIwyFBNxzF4QqKv6IiKgSpEQXoouGnZ57xy4n
            TA7DwEeihUGVvmlkQ8JmGhPhR9A7pnCZh2siWv+2AntC8JTwom2Uep23fUbc5LTx
            MOJWvLCSmUUB2QjhPx/sVc573YHXCFF1X+giLLchYPdc8bAnSRLDxgYUBsxjH9t6
            bMC/v6FPjnmr9pZoSU7RG7ceKKdWYFGtiklt1DqgLYwPhUZwVgCd1P1PZg63vhMm
            C6c+rWN1+ePuVB/pzLWk7v6jWPJkW5kdjvlceX8W/RUjkb4XBpluAvFHKJie7HzU
            ZgEJAhCF+0gjv49dpcnQ5PGDjqs4+hFLajmITsIcOhEt+/pU3CAAawlIP80BWj4a
            h4aX3+4DtSQXhrG4dy0UUPcLBV7E6ue5P+XIiGb3J8VS5D+hIhPW2IFqTd11EsWO
            zyxWR0pITQ==
            =nKC7
            -----END PGP MESSAGE-----
          fp: ACEFCCBBC213DBA5AA1F769879106634907E2B2C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
