apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: csh-flux
  namespace: yebyen-okd4
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: csh-flux
