apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: flux-csh
  namespace: yebyen-okd4
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: flux-csh
    - kind: GitRepository
      name: any-old-app-main
    - kind: GitRepository
      name: any-old-app-prod
