# kind: Service
# apiVersion: v1
# metadata:
#   name: gitno-hephy-pro
#   namespace: ingress-nginx
# spec:
#   ports:
#     - name: traf-ingress-http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 0
# ---
# kind: Endpoints
# apiVersion: v1
# metadata:
#   name: gitno-hephy-pro
#   namespace: ingress-nginx
# subsets:
# - addresses:
#   - ip: 10.17.12.207
#   ports:
#   - port: 80
#     name: traf-ingress-http
#   - port: 443
#     name: traf-ingress
