kind: Service
apiVersion: v1
metadata:
  name: gitno-hephy-pro
  namespace: ingress-nginx
spec:
  ports:
    - name: moo-ingress
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 0
---
kind: Endpoints
apiVersion: v1
metadata:
  name: gitno-hephy-pro
  namespace: ingress-nginx
subsets:
- addresses:
  - ip: 10.17.12.201
  ports:
  - port: 80
    name: moo-ingress
