# ./.github/workflows/release-manifests.yaml
name: Build jsonnet
on:
  push:
    tags: ['release/*']
    branches: ['release']

jobs:
  run:
    name: jsonnet push
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/release/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\/release\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: "Download kubecfg binary to tmp"
        shell: bash
        run: |
          VERSION=0.18.0
          if [ -z $VERSION ]; then
            VERSION=$(curl https://api.github.com/repos/bitnami/kubecfg/releases/latest -sL | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
          fi
          BIN_URL="https://github.com/bitnami/kubecfg/releases/download/v${VERSION}/kubecfg-linux-amd64"
          curl -sL ${BIN_URL} -o /tmp/kubecfg
          chmod +x /tmp/kubecfg
      - name: "Add kubecfg binary to /usr/local/bin"
        shell: bash
        run: |
          sudo cp /tmp/kubecfg /usr/local/bin
      - name: "Cleanup tmp"
        shell: bash
        run: |
          rm -f /tmp/kubecfg
      - name: "Verify correct installation of binary"
        shell: bash
        run: |
          kubecfg version

      - name: kubecfg show
        run: kubecfg show manifests/example.jsonnet > output/production.yaml

      - name: Prepare target branch
        run: ./ci/rake.sh deploy

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'production.yaml'
          branch: deploy
          message: "[ci skip] from ${{ steps.prep.outputs.VERSION }}"
          signoff: true
