---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: wordpress
spec:
  interval: 1h5m0s
  timeout: 2m30s
  url: https://charts.bitnami.com/bitnami

