---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  # serviceAccountName: wordpress-sync
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  chart:
    spec:
      chart: wordpress
      version: '^11.0.12'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 15m0s
  targetNamespace: wordpress
  releaseName: wordpress
  values:
    ingress:
      enabled: false
      hostname: rpiblog.nerdland.local
    service:
      type: LoadBalancer
    wordpressPassword: changeMe7654
    mariadb:
      auth:
        rootPassword: seriouslyPlzchangeMe987346
        password: changeMe987346
